# Generated by Django 4.1 on 2022-08-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.PositiveSmallIntegerField(choices=[(1, 'Суперкомпьютер'), (2, 'Уверенный середнячок'), (3, 'Умная колонка')], default=2, verbose_name='Системные требования')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Название игры')),
                ('release_date', models.DateField(blank=True, verbose_name='Дата релиза')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='pictures/%Y/%m/%d/', verbose_name='Картинка')),
                ('torrent_available', models.BooleanField(default=True, verbose_name='Альтернативно бесплатно?')),
            ],
        ),
    ]
